### ISSUE TITLE
cannot open device '/dev/snd/pcmC0D16c': No such file or directory

### ISSUE THREAD

**Issue by 1036664317** [LineageOS/android_device_xiaomi_msm8998-common#1]
I can't join TG
This is wechat call log
hope to be useful for fix

10-19 12:15:24.182 19545 20648 I TRAE    : [DEBUG] LogTrace[0xb44f7f38--142]: exit [0 ms] set_record_output_samplerate( inited:Y out_sr:16000 rec_sr:16000 rec_out_sr8000) jni/../../../comp/libSpeechEngine/android/AndroidAudioDeviceJavaInterface.cpp 348
10-19 12:15:24.182   784 20655 D audio_route: Apply path: handset-mic
10-19 12:15:24.182 19545 19545 D VideoController: send0x211C2CMsg_Audio_start roomId = 792915009830373903
10-19 12:15:24.184  9384  9384 W VideoBroadCastReceiver: onReceive, action[tencent.video.v2q.AudioEngineReady], seq[0]
10-19 12:15:24.186 19545 19545 W VideoController: onDetectAudioDataIssue, issueType[2048->2048], seq[116]
10-19 12:15:24.187  9452  9529 D MSF.C.NetConnTag: pa ok: 11962
10-19 12:15:24.187  9452  9529 D MSF.C.NetConnTag: netSend ssoSeq:11962 uin:*9121 cmd:ByYjJzs/IAk8IH4EOAsgNC4OIzM 12173 452b0fd
10-19 12:15:24.193   784 20655 W sound_trigger_hw: sound_trigger_hw_call_back: Unknown event 16
10-19 12:15:24.194   784 20655 D soundtrigger: audio_extn_sound_trigger_update_ec_ref_status: update audio echo ref status true
10-19 12:15:24.194   784 20655 E audio_route: unable to find path 'echo-reference-voip'
10-19 12:15:24.194   784 20655 E audio_route: unable to find path 'echo-reference-voip handset'
10-19 12:15:24.194   784 20655 E audio_route: unable to find path 'echo-reference-voip'
10-19 12:15:24.194   784 20655 D msm8974_platform: platform_set_echo_reference: enabling echo-reference-voip
10-19 12:15:24.194   784 20655 E audio_hw_dolby: audio_extn_dolby_ds2_set_endpoint: Dolby set endpint :0x0
10-19 12:15:24.194   784 20655 D soundtrigger: audio HAL using same device 108 as ST
10-19 12:15:24.194   784 20655 D soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_info->id 31 of type 1 for Event 3, with Raise=1
10-19 12:15:24.194   784 20655 D soundtrigger: audio_extn_sound_trigger_update_stream_status: send event 13: usecase id 31, type 1
10-19 12:15:24.194   784 20655 I sound_trigger_platform: platform_stdev_check_and_update_concurrency: Received STREAM event, event type 13, usecase type 3
10-19 12:15:24.194   784 20655 D sound_trigger_platform: platform_stdev_check_and_update_concurrency: dedicated path 0, reset backend 1, tx 2, rx 0,concurrency session not allowed
10-19 12:15:24.194   784 20655 D audio_hw_utils: audio_extn_utils_send_app_type_cfg: usecase->in_snd_device handset-mic
10-19 12:15:24.194   784 20655 D msm8974_platform: platform_split_snd_device: snd_device(108) num devices(0) new_snd_devices(0)
10-19 12:15:24.195   784 20655 E audio_hw_utils: send_app_type_cfg_for_device: Could not get ctl for mixer cmd - Audio Stream Capture 16 App Type Cfg
10-19 12:15:24.195   784 20655 D msm8974_platform: platform_split_snd_device: snd_device(108) num devices(1) new_snd_devices(0)
10-19 12:15:24.195   784 20655 D audio_hw_utils: audio_extn_btsco_get_sample_rate:Not a BT SCO device, need not update sampling rate
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 108, path = 1, app id = 0x1113a, sample rate = 16000
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_asm_topology
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB get asm topology returned = -8
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_adm_topology
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB get adm topology for acdb id = 108, returned = -8
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_audtable
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE
10-19 12:15:24.195   784 20655 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the device 0000006C 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_COMMON_TABLE_SIZE Returned = -19
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
10-19 12:15:24.195   784 20655 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the device 0000006C 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB audproc returned = -19
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_audvoltable
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE
10-19 12:15:24.195   784 20655 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the device 0000006C 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_VOL_STEP_TABLE_SIZE Returned = -19
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE, vol index 0
10-19 12:15:24.195   784 20655 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the device 0000006C 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB AudProc vol returned = -19
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> AUDIO_SET_VOL_CAL cal type = 12
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the appid 0001113A 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB_CMD_GET_AUDPROC_STREAM_TABLE_SIZE Returned = -19
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_audstrmtable
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TABLE_V2
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the appid 0001113A 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB get audstream table returned = -19
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_afe_topology
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_TOPOLOGY_ID
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> GET_AFE_TOPOLOGY_ID for adcd_id 108, Topology Id 112fb
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> send_afe_cal
10-19 12:15:24.195   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE
10-19 12:15:24.195   784 20655 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
10-19 12:15:24.195   784 20655 D         : Failed to fetch the lookup information of the device 0000006C 
10-19 12:15:24.195   784 20655 E ACDB-LOADER: Error: ACDB_CMD_GET_AFE_COMMON_TABLE_SIZE Returned = -19
10-19 12:15:24.196   784 20655 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
10-19 12:15:24.196   784 20655 D         : ACDBFILE_MGR:Read the devices count as zero, please check the acdb file
10-19 12:15:24.196   784 20655 D         : Failed to fetch the lookup information of the device 0000006C 
10-19 12:15:24.196   784 20655 E ACDB-LOADER: Error: ACDB AFE returned = -19
10-19 12:15:24.196   784 20655 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
10-19 12:15:24.196   784 20655 D ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 108 path = 1
10-19 12:15:24.196   784 20655 D ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
10-19 12:15:24.196   784 20655 D audio_hw_primary: enable_audio_route: apply mixer and update path: audio-record-voip
10-19 12:15:24.196   784 20655 E audio_route: unable to find path 'audio-record-voip'
10-19 12:15:24.196   784 20655 D audio_hw_primary: select_devices: done
10-19 12:15:24.196   784 20655 E audio_hw_primary: start_input_stream: cannot open device '/dev/snd/pcmC0D16c': No such file or directory
10-19 12:15:24.196   784 20655 E audio_hw_extn: audio_extn_perf_lock_release: Perf lock release error 
10-19 12:15:24.196   784 20655 D audio_hw_primary: disable_audio_route: reset and update mixer path: audio-record-voip
10-19 12:15:24.196   784 20655 E audio_route: unable to find path 'audio-record-voip'
10-19 12:15:24.196   797   797 D android.hardware.power@1.2-service.xiaomi_msm8998-libperfmgr: AUDIO STREAMING OFF
10-19 12:15:24.196   784 20655 W sound_trigger_hw: sound_trigger_hw_call_back: Unknown event 16

**Comment by Golv** [comment]
I have the same error. How did you solve the problem?

**Comment by 1036664317** [comment]
I didn't fix it, but I used the old audio Hal

**Comment by 1036664317** [comment]
it's work

**Comment by Golv** [comment]
Please, can you explain in more detail, and if possible give links?  I have exactly such errors in the logcats. Microphone does not work during Viber and Skype calls.  In Whatsapp calls microphone works fine.
Thanks!

**Comment by 1036664317** [comment]
I use this
https://github.com/pe-wip/hardware_qcom-caf_audio_msm8998 
my device mix2
Maybe the right way is here
https://github.com/xiaomi-msm8998
